/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

function createDocLink(id: string, label: string) {
    return   {
        type: "link",
        label: `${label} API`,
        href: `/category/${id}-api`
    }
}

const sidebars: SidebarsConfig = {
    techdocSidebar: [
        {
            type: "autogenerated",
            dirName: "tech"
        },
        {
            type: "category",
            label: "API References",
            items: [
                createDocLink("databox", "Databox"),
                createDocLink("expose", "Expose"),
                createDocLink("uploader", "Uploader"),
            ]
        },
    ],
    userdocSidebar: [
        {
            type: "autogenerated",
            dirName: "user",
        },
    ],
    openApiSidebar: [
        {
            type: "category",
            label: "Databox API",
            link: {
                type: "generated-index",
                title: "Phrasea Databox API",
                description:
                    "This is the Phrasea Databox API.",
                slug: "/category/databox-api"
            },
            items: require("./docs/databox_api/sidebar.ts")
        },
    ]
};

export default sidebars;
