/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

function createDocLink(id: string, label: string) {
    return   {
        type: "link",
        label: `${label} API`,
        href: `/category/${id}-api`
    }
}

function createOpenApiSidebarCategory(id: string, label: string) {
    return {
        type: "category",
        label: `${label} API`,
        link: {
            type: "generated-index",
            title: `Phrasea ${label} API`,
            description:
                `This is the Phrasea ${label} API.`,
            slug: `/category/${id}-api`
        },
        items: require(`./docs/${id}_api/sidebar.ts`),
    };
}

const sidebars: SidebarsConfig = {
    techdocSidebar: [
        {
            type: "autogenerated",
            dirName: "tech"
        },
        {
            type: "category",
            label: "API Reference",
            items: [
                createDocLink("databox", "Databox"),
                createDocLink("expose", "Expose"),
                createDocLink("uploader", "Uploader"),
            ]
        },
    ],
    userdocSidebar: [
        {
            type: "autogenerated",
            dirName: "user",
        },
    ],
    openApiSidebar: [
        createOpenApiSidebarCategory("databox", "Databox"),
        createOpenApiSidebarCategory("expose", "Expose"),
        createOpenApiSidebarCategory("uploader", "Uploader"),
    ]
};

export default sidebars;
