/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    techdocSidebar: [
        // {
        //     type: "doc",
        //     id: "intro"
        // },
        {
            type: "autogenerated",
            dirName: "doc/tech"
        },
        {
            type: "link",
            label: "** API **",
            href: "/docs/category/databox-api"
        }
    ],
    userdocSidebar: [
        {
            type: "autogenerated",
            dirName: "doc/user"
        },
    ],
    openApiSidebar: [
        {
            type: "category",
            label: "Databox API",
            link: {
                type: "generated-index",
                title: "Phrasea Databox API",
                description:
                    "This is the Phrasea Databox API.",
                slug: "/category/databox-api"
            },
            items: require("./docs/databox_api/sidebar.ts")
        },
    ]
};

export default sidebars;
